---
title: "textcleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r initialize}
library(dplyr)
library(ggplot2)
library(tidytext)
library(stringr)
```
```{r}

```

```{r the text cleaning}
file <- "1690-1700"
books <- read.csv(str_c(file, "dirty.csv", sep="", collapse=NULL))
texts <- books$booktext
remove_characters <- "ã€^â¦%£ˆ§Â/‰¢*#@²ãºã¨ª"

cleantext <- str_replace_all(texts, "\\[unnumbered\\]", "") %>%
  str_replace_all("Page Â", "") %>%
  str_replace_all("Page [:digit:]", "") %>%
  str_replace_all("page [:digit:]", "") %>%
  str_replace_all("Chapter [:digit:]", "") %>%
  str_replace_all("chapter [:digit:]", "") %>%
  str_replace_all("Chapt. [:digit:]", "") %>%
  str_replace_all("chapt. [:digit:]", "") %>%
  str_replace_all("Chapt [:digit:]", "") %>%
  str_replace_all("chapt [:digit:]", "") %>%
  str_replace_all("\\[Illustration\\]", "") %>%
  str_replace_all("\\[illustration\\]", "") %>%
  str_replace_all("u009d", "") %>%
  str_replace_all("[^:alpha:\\.&:space:]", "") %>%
  str_replace_all("&", "and") %>%
  str_replace_all(" andc ", "&c") %>%
  str_replace_all(" andc.", "&c.") %>%
  str_replace_all("\\.", "") %>%
  str_to_lower()

books$booktext <- cleantext
write.csv(books, str_c(file, ".csv", sep="", collapse=NULL))
```
