---
title: "Visualizations"
author: 'Team 19: For the Love of Greed'
date: "7/2/2020"
output:
  pdf_document: default
  html_document: default
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r load packages}
library(tidyverse)
library(stringi)
```

```{r Wrangling Similarity}
df_similarity <- tibble(years=c("1470-1494", "1495-1519","1520-1544","1545-1569",
                "1570-1594","1595-1619","1620-1644","1645-1669",
                "1670-1700"),
                luxury=c(-0.17466319, -0.30258608, -0.37691566,
                      -0.18834212, 0.26263857, 0.44608718, 0.42523912, 
                      0.31434003, 0.40818825),
                disease=c(0.8172742, 0.65451854, 0.6040485, 0.39209074, 
                          0.33092698, 0.3218253, 0.21741053, 0.13698031, 
                          0.18832971))

df_similarity <- df_similarity %>%
  select(years, luxury, disease) %>%
  gather(key = "variable", value = "value", -years)
```

```{r Without labels}
plot_without_labels <- ggplot(data=df_similarity, aes(x=years, group = 1)) +
  geom_line(aes(y = luxury), color = "darkred")+
  geom_line(aes(y = disease), color="steelblue")+ 
  scale_color_manual(values = c("darkred", "steelblue"))
```
```{r Cosine}
cosine_plot <- ggplot(df_similarity, aes(x = years, y = value, group = variable)) + 
  geom_line(aes(color = variable), size = 2) + 
  scale_color_manual(values = c("darkred", "steelblue")) + 
  labs(
    title = "Consume becomes economic over the late middle ages",
    subtitle = "Using Cosine Similarity Test",
    x = "Time",
    y = "Similarity",
    color = "Comsume \ncompared to:"
  ) +
  theme_classic() +
  theme(text = element_text(size=20),
        axis.text=element_text(size=10))

cosine_plot
```
```{r Euclidean}
df_euclidean <- tibble(years=c("1470-1494", "1495-1519","1520-1544","1545-1569",
                "1570-1594","1595-1619","1620-1644","1645-1669",
                "1670-1700"),
                luxury=c(1.1746631860733032, 1.3025860786437988, 1.3769156634807587, 1.188342124223709, 0.7373614311218262, 0.5539128184318542, 0.5747608840465546, 0.6856599748134613, 0.5918117463588715),
                disease=c(0.18272578716278076, 0.3454814553260803, 0.395951509475708, 0.6079092621803284, 0.6690730154514313, 0.6781747043132782, 0.782589465379715, 0.8630196899175644, 0.8116702884435654))

euclidean_plot <- df_euclidean %>%
  select(years, luxury, disease) %>%
  gather(key = "variable", value = "value", -years) %>%
  ggplot(aes(x = years, y = value, group = variable)) + 
  geom_line(aes(color = variable), size = 2) + 
  scale_color_manual(values = c("darkred", "steelblue")) + 
  labs(
    title = "Consume becomes economic over the late middle ages",
    subtitle = "Using Euclidean Distance",
    x = "Time",
    y = "Distance",
    color = "Comsume \ncompared to:"
  ) +
  theme_classic() +
  theme(text = element_text(size=20),
        axis.text=element_text(size=10))

euclidean_plot
```



