---
title: "vis_zscore"
author: "Team 19"
date: "7/10/2020"
output: html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r load packages}
library(tidyverse)
library(stringi)
library(ggrepel)
library(stringr)
library(data.table)
```

```{r load csvs}
csv1 <- fread("CSVs/GenderAxisSimilarities.csv")
```

# Two Sided

http://www.cookbook-r.com/Manipulating_data/Converting_data_between_wide_and_long_format/
wide>long

```{r wrangling}
df_plot_z <- csv1 %>%
  select("Words", ends_with("Z-Scores"))%>%
  drop_na() %>%
  rename(
    "1470" = "1470-1494 Z-Scores",
    "1495" = "1495-1519 Z-Scores",
    "1520" = "1520-1544 Z-Scores",
    "1545" = "1545-1569 Z-Scores",
    "1570" = "1570-1594 Z-Scores",
    "1595" = "1595-1619 Z-Scores",
    "1620" = "1620-1644 Z-Scores",
#    "1645" = "1645-1669 Z-Scores",
#    "1670" = "1670-1700 Z-Scores"
  )
```

```{r find significant words, eval=FALSE, include=FALSE}
significant_words <- df_plot_z %>%
  gather(years, zscore, "1470":"1620") %>%
#  gather(years, zscore, "1470":"1570") %>%
  mutate(Words = as.factor(Words))%>%
  filter((zscore < -1.96 | zscore > 1.96)) %>%
  distinct(Words) %>%
  pull(Words) 

significant_words 
```

```{r gather wide to long}
df_plot_z <- df_plot_z %>%
  gather(years, zscore, "1470":"1620") %>%
#  gather(years, zscore, "1470":"1570") %>%
  mutate(Words = as.factor(Words)) %>%
  filter(Words %in% c('consumption', 'consume', 'cupidity', 'cupiditas', 'curiosity', 'curiositas',
           'greed', 'desire', 'appetite', 'lust', 'libido', 'covetousness', 'avarice',
           'possess', 'possession', 'possessing', 'busy', 'businesse', 'need', 'necessity',
           'necessary', 'needing', 'meed', 'bowgeor', 'bougeor', 'budge', 'wastour',
           'waster', 'wasture', 'wastoure', 'speculation', 'debt', 'debitum', 'expense',
           'gain', 'miser', 'fortune', 'use', 'usury', 'interest',
           'interesse', 'consumptioner')) %>%
  filter(Words %in% c('possession', 'greed', 'desire', 'consumption'))
#  %>% filter(Words %in% significant_words) #use if significant words
```


```{r plot1}
plot1 <- df_plot_z %>%
  mutate(label = if_else(years == max(years), as.character(Words), NA_character_)) %>%
#  select(years, luxury, disease) %>%
#  gather(key = "variable", value = "value", -years) %>%
  ggplot(aes(x = years, y = zscore, group = Words)) + 
  geom_line(aes(color = Words), size = 1) + 
  geom_hline(yintercept=1.96, linetype = "dashed") + 
  geom_hline(yintercept=-1.96, linetype = "dashed") +
  scale_color_discrete(guide = FALSE) + 
  geom_label_repel(aes(label= label),
                  nudge_x = 1,
                  na.rm = TRUE,
                  direction = "both")+
  theme(text = element_text(size=20),
        axis.text=element_text(size=10))

plot1
```
```{r plot 2}
plot2 <- df_plot_z %>%
  ggplot(aes(x = years, y = zscore, group = Words)) + 
  geom_line(aes(color = Words), size = 1) + 
  geom_hline(yintercept=1.96, linetype = "dashed") + 
  geom_hline(yintercept=-1.96, linetype = "dashed") +
  scale_color_discrete(guide = FALSE) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = -1.96, alpha = .2, fill = "blue")+
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 1.96, ymax = Inf, alpha = .2, fill = "red")+
  theme(text = element_text(size=20),
        axis.text=element_text(size=10)) +
  theme(
    text = element_text(size = 25),
    legend.position="none",
    strip.text.x = element_text(size = 25),
    axis.text = element_text(size = 20),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    ) +
#  scale_color_manual(values=c('#000000','#000000','#000000','#000000'))+
  scale_y_continuous(name = "Z-Score", breaks = c(-1.96, 0, 1.96)) + 
  facet_wrap(~Words, nrow = 2) + 
  labs(
    title = "Consumption-related words and their gender contexts",
    x= "Years"
    )

plot2
```

```{r poster}

df_poster <- csv1 %>%
  select("Words", ends_with("Z-Scores"))%>%
  drop_na() %>%
  rename(
    "1470" = "1470-1494 Z-Scores",
    "1495" = "1495-1519 Z-Scores",
    "1520" = "1520-1544 Z-Scores",
    "1545" = "1545-1569 Z-Scores",
    "1570" = "1570-1594 Z-Scores",
    "1595" = "1595-1619 Z-Scores",
    "1620" = "1620-1644 Z-Scores",
    "1645" = "1645-1669 Z-Scores",
    "1670" = "1670-1700 Z-Scores",
  )

#significant_words

significant_words <- df_poster %>%
  gather(years, zscore, "1470":"1670") %>%
  mutate(Words = as.factor(Words))%>%
  filter((zscore < -1.96 | zscore > 1.96)) %>%
  distinct(Words) %>%
  pull(Words) 

#facet labels

facet_names <- list(
  'possession'="Possession",
  'greed'="Greed",
  'consume'="Consume",
  'consumption'="Consumption"
)

facet_labeller <- function(variable,value){
  return(facet_names[value])
}

df_poster <- df_poster %>%
  gather(years, zscore, "1470":"1670") %>%
  mutate(Words = as.factor(Words))%>%
  filter(Words %in% c('possession', 'greed', 'consume', 'consumption')) 
plot3 <- df_poster %>%
  ggplot(aes(x = years, y = zscore, group = Words)) + 
  geom_line(aes(color = Words), size = 2) + 
  geom_hline(yintercept=1.96, linetype = "dashed") + 
  geom_hline(yintercept=-1.96, linetype = "dashed") +
  annotate("text", x = 5, y = 2.8, size = 10,
           label = "paste(\"Female, \",italic(p), \" < 0.05\")", parse = TRUE, colour = "red") + 
  annotate("text", x = 5, y = -2.8, size = 10, 
           label = "paste(\"Male, \",italic(p), \" < 0.05\")", parse = TRUE, colour = "blue") +
  scale_color_discrete(guide = FALSE) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = -1.96, alpha = .2, fill = "blue")+
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 1.96, ymax = Inf, alpha = .2, fill = "red")+
  scale_y_continuous(name = "Z-Score", breaks = c(-1.95, 0, 1.95), limits = c(-4, 4)) + 
  scale_x_discrete(name = "Years", breaks = c("1470", "1570")) +
  facet_wrap(~Words, nrow = 2) + 
  labs(
    title = "Consumption-related words and \ntheir gender contexts"
    ) + 
  scale_color_manual(values=c('#000000','#000000','#000000','#000000'))+
  theme(
    text = element_text(size = 30),
    legend.position="none",
    axis.text = element_text(size = 25),
    strip.text.x = element_text(
        size = 30
        )
    ) 


plot3
```

```{r}
ggsave("plot3v3.png", plot3, units = "in", width = 850/100, height = 800/100 )
```

Save as W = 850, L = 800




